package me.gb2022.quantum3d.device.listener;

import me.gb2022.quantum3d.device.Keyboard;
import me.gb2022.quantum3d.device.KeyboardButton;
import me.gb2022.quantum3d.device.Window;

/**
 * A listener interface for receiving keyboard-related events.
 * Implementing classes can override these methods to respond to keyboard events.
 */
public interface KeyboardListener {

    /**
     * Called when a key is pressed.
     *
     * @param window   The window associated with the event.
     * @param keyboard The keyboard instance.
     * @param key      The pressed key.
     */
    default void onKeyPressEvent(Window window, Keyboard keyboard, KeyboardButton key) {
    }

    /**
     * Called when a key is released.
     *
     * @param window   The window associated with the event.
     * @param keyboard The keyboard instance.
     * @param key      The released key.
     */
    default void onKeyReleaseEvent(Window window, Keyboard keyboard, KeyboardButton key) {
    }

    /**
     * Called repeatedly while a key is held down.
     *
     * @param window   The window associated with the event.
     * @param keyboard The keyboard instance.
     * @param key      The held key.
     */
    default void onKeyHoldEvent(Window window, Keyboard keyboard, KeyboardButton key) {
    }

    /**
     * Called when a Unicode character is generated by a key press.
     *
     * @param window    The window associated with the event.
     * @param keyboard  The keyboard instance.
     * @param codepoint The Unicode codepoint of the generated character.
     */
    default void onCharEvent(Window window, Keyboard keyboard, char codepoint) {
    }
}