/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ink_flybird_quantum3d_native_access_VertexBuilderAccess */

#ifndef _Included_ink_flybird_quantum3d_native_access_VertexBuilderAccess
#define _Included_ink_flybird_quantum3d_native_access_VertexBuilderAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ink_flybird_quantum3d_native_access_VertexBuilderAccess
 * Method:    create
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_ink_flybird_quantum3d_native_1access_VertexBuilderAccess_create
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ink_flybird_quantum3d_native_access_VertexBuilderAccess
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ink_flybird_quantum3d_native_1access_VertexBuilderAccess_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ink_flybird_quantum3d_native_access_VertexBuilderAccess
 * Method:    begin
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ink_flybird_quantum3d_native_1access_VertexBuilderAccess_begin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ink_flybird_quantum3d_native_access_VertexBuilderAccess
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ink_flybird_quantum3d_native_1access_VertexBuilderAccess_end
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ink_flybird_quantum3d_native_access_VertexBuilderAccess
 * Method:    vertex
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_ink_flybird_quantum3d_native_1access_VertexBuilderAccess_vertex
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     ink_flybird_quantum3d_native_access_VertexBuilderAccess
 * Method:    color
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_ink_flybird_quantum3d_native_1access_VertexBuilderAccess_color
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ink_flybird_quantum3d_native_access_VertexBuilderAccess
 * Method:    tex
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_ink_flybird_quantum3d_native_1access_VertexBuilderAccess_tex
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     ink_flybird_quantum3d_native_access_VertexBuilderAccess
 * Method:    normal
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_ink_flybird_quantum3d_native_1access_VertexBuilderAccess_normal
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     ink_flybird_quantum3d_native_access_VertexBuilderAccess
 * Method:    uploadPointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ink_flybird_quantum3d_native_1access_VertexBuilderAccess_uploadPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ink_flybird_quantum3d_native_access_VertexBuilderAccess
 * Method:    uploadBuffer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ink_flybird_quantum3d_native_1access_VertexBuilderAccess_uploadBuffer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ink_flybird_quantum3d_native_access_VertexBuilderAccess
 * Method:    uploadInterleaved
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ink_flybird_quantum3d_native_1access_VertexBuilderAccess_uploadInterleaved
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
