/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ink_flybird_quantum3d_native_access_NativeContext */

#ifndef _Included_ink_flybird_quantum3d_native_access_NativeContext
#define _Included_ink_flybird_quantum3d_native_access_NativeContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ink_flybird_quantum3d_native_access_NativeContext
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ink_flybird_quantum3d_native_1access_NativeContext_load
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
