[meta]
id = "cubecraft_client"
version = "1.0.0"
class = "net.cubecraft.client.internal.CubecraftClientInternalMod"
side = "client"

[dependencies-client]
cubecraft_core = "__any__"
cubecraft_server="__any__"

[info]
name = "Cubecraft-Client"
author = "GrassBlock2022"
website = "https://github.com/CubecraftDevelopment"
description = "Basic client framework."
